export const ADD_TODO='ADD_TODO';
export const REMOVE_TODO='REMOVE_TODO';
export const MARK_COMPLETED='MARK_COMPLETED';
export const MARK_INCOMPLETED='MARK_INCOMPLETED';
export const TOOGLE_TODO='TOOGLE_TODO';
export const FILTER_TODO='FILTER_TODO';
export const ALL_COMPLETED='ALL_COMPLETED';
export const UPDATE_SEARCH='UPDATE_SEARCH';